//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Box : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Box(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Box obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Box() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          boxPINVOKE.delete_Box(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Box(int len, int bre, int hei) : this(boxPINVOKE.new_Box(len, bre, hei), true) {
  }

  public double length {
    set {
      boxPINVOKE.Box_length_set(swigCPtr, value);
    } 
    get {
      double ret = boxPINVOKE.Box_length_get(swigCPtr);
      return ret;
    } 
  }

  public double breadth {
    set {
      boxPINVOKE.Box_breadth_set(swigCPtr, value);
    } 
    get {
      double ret = boxPINVOKE.Box_breadth_get(swigCPtr);
      return ret;
    } 
  }

  public double height {
    set {
      boxPINVOKE.Box_height_set(swigCPtr, value);
    } 
    get {
      double ret = boxPINVOKE.Box_height_get(swigCPtr);
      return ret;
    } 
  }

  public double getVolume() {
    double ret = boxPINVOKE.Box_getVolume(swigCPtr);
    return ret;
  }

  public void setLength(double len) {
    boxPINVOKE.Box_setLength(swigCPtr, len);
  }

  public void setBreadth(double bre) {
    boxPINVOKE.Box_setBreadth(swigCPtr, bre);
  }

  public void setHeight(double hei) {
    boxPINVOKE.Box_setHeight(swigCPtr, hei);
  }

}
